# Generated by Django 6.0.5 on 2026-07-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_background',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
